# Generated by Django 2.1 on 2018-09-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FoodMaterial')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_effect', models.IntegerField()),
                ('food_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FoodMaterial')),
                ('physique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Physique')),
            ],
        ),
        migrations.AddField(
            model_name='menuclassification',
            name='cure_occupation',
            field=models.ManyToManyField(to='mainapp.Occupation'),
        ),
        migrations.AddField(
            model_name='menuclassification',
            name='menu_effect',
            field=models.ManyToManyField(to='mainapp.Menu'),
        ),
        migrations.AddField(
            model_name='physicalproperty',
            name='physical_state',
            field=models.ManyToManyField(to='mainapp.Physique'),
        ),
        migrations.AddField(
            model_name='foodmaterial',
            name='cook_quantity',
            field=models.ManyToManyField(through='mainapp.CookQuantity', to='mainapp.Menu'),
        ),
        migrations.AddField(
            model_name='foodmaterial',
            name='material_effect',
            field=models.ManyToManyField(through='mainapp.MaterialEffect', to='mainapp.Physique'),
        ),
    ]
