# Generated by Django 2.1 on 2018-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180907_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuclassification',
            name='cure_occupation',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Occupation'),
        ),
    ]
