# Generated by Django 2.1 on 2018-09-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180908_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='practice',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
