# Generated by Django 2.1 on 2018-09-12 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180912_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='physical_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Physique'),
        ),
    ]
