# Generated by Django 2.1 on 2018-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180912_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sex',
            field=models.IntegerField(default=1),
        ),
    ]
