# Generated by Django 2.1 on 2018-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_myuser_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmaterial',
            name='cook_quantity',
        ),
        migrations.AddField(
            model_name='menu',
            name='cook_quantity',
            field=models.ManyToManyField(through='mainapp.CookQuantity', to='mainapp.FoodMaterial'),
        ),
    ]
