# Generated by Django 2.1 on 2018-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180914_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physique',
            name='exercise_method',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='physique',
            name='physical_feature',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cookquantity',
            unique_together={('menu', 'material')},
        ),
    ]
