# Generated by Django 2.1 on 2018-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180916_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookquantity',
            name='quantity',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='calorie',
            field=models.IntegerField(default=-1),
        ),
    ]
