# Generated by Django 2.1 on 2018-09-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180917_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialeffect',
            name='food_material',
        ),
        migrations.RemoveField(
            model_name='materialeffect',
            name='physique',
        ),
        migrations.RemoveField(
            model_name='physicalproperty',
            name='physical_state',
        ),
        migrations.RemoveField(
            model_name='foodmaterial',
            name='material_effect',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='physical_name',
        ),
        migrations.DeleteModel(
            name='MaterialEffect',
        ),
        migrations.DeleteModel(
            name='PhysicalProperty',
        ),
    ]
