# Generated by Django 2.1 on 2018-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180917_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='physique',
            name='cure_menu_classification',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.MenuClassification'),
        ),
    ]
