# Generated by Django 2.1 on 2018-09-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180919_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='occupation_name',
        ),
    ]
