# Generated by Django 2.1 on 2018-09-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_myuser_occupation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='occupation_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Occupation'),
        ),
    ]
