# Generated by Django 2.1 on 2018-09-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_myuser_occupation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuclassification',
            name='cure_occupation',
        ),
    ]
