# Generated by Django 2.1 on 2018-09-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_menuclassification_cure_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physique',
            name='cure_menu_classification',
        ),
        migrations.AddField(
            model_name='physique',
            name='cure_material',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.FoodMaterial'),
        ),
    ]
