# Generated by Django 2.1.1 on 2018-09-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('menu_classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.MenuClassification')),
                ('elements', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Element')),
            ],
        ),
        migrations.AddField(
            model_name='occupation',
            name='elements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Element'),
        ),
        migrations.AddField(
            model_name='physique',
            name='elements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Element'),
        ),
    ]
