# Generated by Django 2.1.1 on 2018-09-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20180928_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='test',
            field=models.FloatField(default=0),
        ),
    ]
