# Generated by Django 2.1.1 on 2018-09-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_element_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='test',
        ),
    ]
