# Generated by Django 2.1.1 on 2018-09-29 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20180929_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='elements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Element'),
        ),
    ]
