# Generated by Django 2.1.1 on 2018-09-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_menu_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='bmi_classification',
            field=models.IntegerField(default=-1),
        ),
    ]
