# Generated by Django 2.1.1 on 2018-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_occupation_bmi_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='illness',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Illness'),
        ),
    ]
