# Generated by Django 2.1.1 on 2018-09-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20180930_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
