# Generated by Django 2.1.1 on 2018-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20180930_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bmi',
            field=models.IntegerField(default=-1),
        ),
    ]
