# Generated by Django 2.1.1 on 2018-10-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20180930_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='eaten_elements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Element'),
        ),
    ]
