# Generated by Django 2.1.1 on 2018-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_trick'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_breakfast',
            field=models.IntegerField(default=0),
        ),
    ]
