# Generated by Django 2.1.1 on 2018-10-31 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_menu_is_breakfast'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=True, to='mainapp.Menu')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='menu_history',
            field=models.ManyToManyField(blank=True, null=True, through='mainapp.History', to='mainapp.Menu'),
        ),
    ]
